### ISSUE TITLE
Doesn't appear to be working

### ISSUE THREAD

**Issue by ellwoods** [bulutfor/youtrack_vscode#1]
Hi,

I've just installed this add on and when I try to use the list function I get the error - 

command 'youtrack.list' not found
  | onDidNotificationChange | @ | notificationsAlerts.ts:40
-- | -- | -- | --
  | _register.model.onDidNotificationChange.e | @ | notificationsAlerts.ts:26
  | fire | @ | event.ts:572
  | addNotification | @ | notifications.ts:156
  | error | @ | notificationService.ts:57
  | (anonymous) | @ | statusbarPart.ts:744
  | a | @ | errors.ts:199
  | _tickCallback | @ | internal/process/next_tick.js:68
  | Promise.then (async) |   |  
  | l | @ | errors.ts:199
  | (anonymous) | @ | errors.ts:199
  | n | @ | errors.ts:199
  | executeCommand | @ | statusbarPart.ts:731
  | entry.e.command.entry.command.e.command.commandListener.value.w.addDisposableListener | @ | statusbarPart.ts:695

Any suggestions?

This happened with the following setup (Insiders) but it also happened with standard VS Code too on the same machine

Version: 1.39.0-insider (user setup)
Commit: 211fa02efe8c041fd7baa8ec3dce199d5185aa44
Date: 2019-09-11T06:18:37.576Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

thanks

**Comment by KiPSOFT** [comment]
Hi,

I'm reproduce this bug. Please uninstall extension in vscode and remove extension folder.  For mac: ~/.vscode/extensions/bulut4.youtrack-0.0.17

And reinstall extension.
